name: Maven Verify
on:
  pull_request:
    branches:
      - master

jobs:
  nldi-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Create docker network
        run: docker network create --subnet=172.26.0.0/16 nldi
      - name: Verify with Maven
        run: mvn verify -DTESTING_DATABASE_PORT=5445 -DTESTING_DATABASE_ADDRESS=localhost -DTESTING_DATABASE_NETWORK=nldi -f pom.xml
